<Project Sdk="Godot.NET.Sdk/4.5.0">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MetadataExtractor" Version="2.8.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.11" />
  </ItemGroup>
  <ItemGroup>
    <Content Include=".gitattributes" />
    <Content Include=".gitignore" />
    <Content Include=".gutconfig.json" />
    <Content Include=".mise.toml" />
    <Content Include=".pre-commit-config.yaml" />
    <Content Include="addons\easy_charts\control_charts\chart.gd" />
    <Content Include="addons\easy_charts\control_charts\chart.gd.uid" />
    <Content Include="addons\easy_charts\control_charts\chart.tscn" />
    <Content Include="addons\easy_charts\control_charts\dark_chart_theme.tres" />
    <Content Include="addons\easy_charts\control_charts\default_chart_theme.tres" />
    <Content Include="addons\easy_charts\control_charts\domain\chart_axis_domain.gd" />
    <Content Include="addons\easy_charts\control_charts\domain\chart_axis_domain.gd.uid" />
    <Content Include="addons\easy_charts\control_charts\plotters\area_plotter.gd" />
    <Content Include="addons\easy_charts\control_charts\plotters\area_plotter.gd.uid" />
    <Content Include="addons\easy_charts\control_charts\plotters\bar_plotter.gd" />
    <Content Include="addons\easy_charts\control_charts\plotters\bar_plotter.gd.uid" />
    <Content Include="addons\easy_charts\control_charts\plotters\function_plotter.gd" />
    <Content Include="addons\easy_charts\control_charts\plotters\function_plotter.gd.uid" />
    <Content Include="addons\easy_charts\control_charts\plotters\line_plotter.gd" />
    <Content Include="addons\easy_charts\control_charts\plotters\line_plotter.gd.uid" />
    <Content Include="addons\easy_charts\control_charts\plotters\pie_plotter.gd" />
    <Content Include="addons\easy_charts\control_charts\plotters\pie_plotter.gd.uid" />
    <Content Include="addons\easy_charts\control_charts\plotters\scatter_plotter.gd" />
    <Content Include="addons\easy_charts\control_charts\plotters\scatter_plotter.gd.uid" />
    <Content Include="addons\easy_charts\examples\area_chart\area_chart_example.gd" />
    <Content Include="addons\easy_charts\examples\area_chart\area_chart_example.gd.uid" />
    <Content Include="addons\easy_charts\examples\area_chart\area_chart_example.tscn" />
    <Content Include="addons\easy_charts\examples\bar_chart\bar_chart_example.gd" />
    <Content Include="addons\easy_charts\examples\bar_chart\bar_chart_example.gd.uid" />
    <Content Include="addons\easy_charts\examples\bar_chart\bar_chart_example.tscn" />
    <Content Include="addons\easy_charts\examples\line_chart\line_chart_example.gd" />
    <Content Include="addons\easy_charts\examples\line_chart\line_chart_example.gd.uid" />
    <Content Include="addons\easy_charts\examples\line_chart\line_chart_example.tscn" />
    <Content Include="addons\easy_charts\examples\multiplot\multiplot_example.gd" />
    <Content Include="addons\easy_charts\examples\multiplot\multiplot_example.gd.uid" />
    <Content Include="addons\easy_charts\examples\multiplot\multiplot_example.tscn" />
    <Content Include="addons\easy_charts\examples\pie_chart\pie_chart_example.gd" />
    <Content Include="addons\easy_charts\examples\pie_chart\pie_chart_example.gd.uid" />
    <Content Include="addons\easy_charts\examples\pie_chart\pie_chart_example.tscn" />
    <Content Include="addons\easy_charts\examples\scatter_chart\scatter_chart_example.gd" />
    <Content Include="addons\easy_charts\examples\scatter_chart\scatter_chart_example.gd.uid" />
    <Content Include="addons\easy_charts\examples\scatter_chart\scatter_chart_example.tscn" />
    <Content Include="addons\easy_charts\examples\scatter_chart_discrete\blackbird_icon.png" />
    <Content Include="addons\easy_charts\examples\scatter_chart_discrete\blackbird_icon.png.import" />
    <Content Include="addons\easy_charts\examples\scatter_chart_discrete\icon_licences.txt" />
    <Content Include="addons\easy_charts\examples\scatter_chart_discrete\nightingale_icon.png" />
    <Content Include="addons\easy_charts\examples\scatter_chart_discrete\nightingale_icon.png.import" />
    <Content Include="addons\easy_charts\examples\scatter_chart_discrete\scatter_chart_discrete.gd" />
    <Content Include="addons\easy_charts\examples\scatter_chart_discrete\scatter_chart_discrete.gd.uid" />
    <Content Include="addons\easy_charts\examples\scatter_chart_discrete\scatter_chart_discrete.tscn" />
    <Content Include="addons\easy_charts\examples\simple_chart\simple_chart_example.gd" />
    <Content Include="addons\easy_charts\examples\simple_chart\simple_chart_example.gd.uid" />
    <Content Include="addons\easy_charts\examples\simple_chart\simple_chart_example.tscn" />
    <Content Include="addons\easy_charts\examples\theming\theming_example.gd" />
    <Content Include="addons\easy_charts\examples\theming\theming_example.gd.uid" />
    <Content Include="addons\easy_charts\examples\theming\theming_example.tscn" />
    <Content Include="addons\easy_charts\examples\theming\theming_example_blue.tres" />
    <Content Include="addons\easy_charts\examples\theming\theming_example_funny.tres" />
    <Content Include="addons\easy_charts\icon.svg" />
    <Content Include="addons\easy_charts\icon.svg.import" />
    <Content Include="addons\easy_charts\plugin.cfg" />
    <Content Include="addons\easy_charts\plugin.gd" />
    <Content Include="addons\easy_charts\plugin.gd.uid" />
    <Content Include="addons\easy_charts\templates.json" />
    <Content Include="addons\easy_charts\utilities\assets\OpenSans-VariableFont_wdth,wght.ttf" />
    <Content Include="addons\easy_charts\utilities\assets\OpenSans-VariableFont_wdth,wght.ttf.import" />
    <Content Include="addons\easy_charts\utilities\classes\plotting\bar.gd" />
    <Content Include="addons\easy_charts\utilities\classes\plotting\bar.gd.uid" />
    <Content Include="addons\easy_charts\utilities\classes\plotting\chart_properties.gd" />
    <Content Include="addons\easy_charts\utilities\classes\plotting\chart_properties.gd.uid" />
    <Content Include="addons\easy_charts\utilities\classes\plotting\function.gd" />
    <Content Include="addons\easy_charts\utilities\classes\plotting\function.gd.uid" />
    <Content Include="addons\easy_charts\utilities\classes\plotting\point.gd" />
    <Content Include="addons\easy_charts\utilities\classes\plotting\point.gd.uid" />
    <Content Include="addons\easy_charts\utilities\classes\structures\array_operations.gd" />
    <Content Include="addons\easy_charts\utilities\classes\structures\array_operations.gd.uid" />
    <Content Include="addons\easy_charts\utilities\classes\structures\data_frame.gd" />
    <Content Include="addons\easy_charts\utilities\classes\structures\data_frame.gd.uid" />
    <Content Include="addons\easy_charts\utilities\classes\structures\matrix.gd" />
    <Content Include="addons\easy_charts\utilities\classes\structures\matrix.gd.uid" />
    <Content Include="addons\easy_charts\utilities\classes\structures\matrix_generator.gd" />
    <Content Include="addons\easy_charts\utilities\classes\structures\matrix_generator.gd.uid" />
    <Content Include="addons\easy_charts\utilities\containers\canvas\canvas.gd" />
    <Content Include="addons\easy_charts\utilities\containers\canvas\canvas.gd.uid" />
    <Content Include="addons\easy_charts\utilities\containers\canvas\plot_box\grid_box.gd" />
    <Content Include="addons\easy_charts\utilities\containers\canvas\plot_box\grid_box.gd.uid" />
    <Content Include="addons\easy_charts\utilities\containers\canvas\plot_box\plot_box.gd" />
    <Content Include="addons\easy_charts\utilities\containers\canvas\plot_box\plot_box.gd.uid" />
    <Content Include="addons\easy_charts\utilities\containers\data_tooltip\data_tooltip.gd" />
    <Content Include="addons\easy_charts\utilities\containers\data_tooltip\data_tooltip.gd.uid" />
    <Content Include="addons\easy_charts\utilities\containers\data_tooltip\data_tooltip.tscn" />
    <Content Include="addons\easy_charts\utilities\containers\legend\function_label.gd" />
    <Content Include="addons\easy_charts\utilities\containers\legend\function_label.gd.uid" />
    <Content Include="addons\easy_charts\utilities\containers\legend\function_label.tscn" />
    <Content Include="addons\easy_charts\utilities\containers\legend\function_legend.gd" />
    <Content Include="addons\easy_charts\utilities\containers\legend\function_legend.gd.uid" />
    <Content Include="addons\easy_charts\utilities\containers\legend\function_legend.tscn" />
    <Content Include="addons\easy_charts\utilities\containers\legend\function_type.gd" />
    <Content Include="addons\easy_charts\utilities\containers\legend\function_type.gd.uid" />
    <Content Include="addons\easy_charts\utilities\icons\linechart.svg" />
    <Content Include="addons\easy_charts\utilities\icons\linechart.svg.import" />
    <Content Include="addons\easy_charts\utilities\scripts\ec_utilities.gd" />
    <Content Include="addons\easy_charts\utilities\scripts\ec_utilities.gd.uid" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.android.template_debug.arm64.so" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.android.template_debug.x86_64.so" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.android.template_release.arm64.so" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.android.template_release.x86_64.so" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.ios.template_debug.arm64.dylib" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.ios.template_debug.xcframework\Info.plist" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.ios.template_debug.xcframework\ios-arm64\libgdsqlite.ios.template_debug.a" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.ios.template_debug.xcframework\ios-arm64_x86_64-simulator\libgdsqlite.ios.template_debug.simulator.a" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.ios.template_release.arm64.dylib" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.ios.template_release.xcframework\Info.plist" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.ios.template_release.xcframework\ios-arm64\libgdsqlite.ios.template_release.a" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.ios.template_release.xcframework\ios-arm64_x86_64-simulator\libgdsqlite.ios.template_release.simulator.a" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.linux.template_debug.x86_64.so" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.linux.template_release.x86_64.so" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.macos.template_debug.framework\libgdsqlite.macos.template_debug" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.macos.template_debug.framework\libmacos.libgdsqlite.template_debug" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.macos.template_debug.framework\Resources\Info.plist" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.macos.template_release.framework\libgdsqlite.macos.template_release" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.macos.template_release.framework\libmacos.libgdsqlite.template_release" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.macos.template_release.framework\Resources\Info.plist" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.web.template_debug.wasm32.wasm" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.web.template_release.wasm32.wasm" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.windows.template_debug.x86_64.dll" />
    <Content Include="addons\godot-sqlite\bin\libgdsqlite.windows.template_release.x86_64.dll" />
    <Content Include="addons\godot-sqlite\bin\libgodot-cpp.ios.template_debug.xcframework\Info.plist" />
    <Content Include="addons\godot-sqlite\bin\libgodot-cpp.ios.template_debug.xcframework\ios-arm64\libgodot-cpp.ios.template_debug.arm64.a" />
    <Content Include="addons\godot-sqlite\bin\libgodot-cpp.ios.template_debug.xcframework\ios-arm64_x86_64-simulator\libgodot-cpp.ios.template_debug.universal.simulator.a" />
    <Content Include="addons\godot-sqlite\bin\libgodot-cpp.ios.template_release.xcframework\Info.plist" />
    <Content Include="addons\godot-sqlite\bin\libgodot-cpp.ios.template_release.xcframework\ios-arm64\libgodot-cpp.ios.template_release.arm64.a" />
    <Content Include="addons\godot-sqlite\bin\libgodot-cpp.ios.template_release.xcframework\ios-arm64_x86_64-simulator\libgodot-cpp.ios.template_release.universal.simulator.a" />
    <Content Include="addons\godot-sqlite\gdsqlite.gdextension" />
    <Content Include="addons\godot-sqlite\gdsqlite.gdextension.uid" />
    <Content Include="addons\godot-sqlite\godot-sqlite.gd" />
    <Content Include="addons\godot-sqlite\godot-sqlite.gd.uid" />
    <Content Include="addons\godot-sqlite\LICENSE.md" />
    <Content Include="addons\godot-sqlite\plugin.cfg" />
    <Content Include="addons\gut\autofree.gd" />
    <Content Include="addons\gut\autofree.gd.uid" />
    <Content Include="addons\gut\awaiter.gd" />
    <Content Include="addons\gut\awaiter.gd.uid" />
    <Content Include="addons\gut\cli\change_project_warnings.gd" />
    <Content Include="addons\gut\cli\change_project_warnings.gd.uid" />
    <Content Include="addons\gut\cli\gut_cli.gd" />
    <Content Include="addons\gut\cli\gut_cli.gd.uid" />
    <Content Include="addons\gut\cli\optparse.gd" />
    <Content Include="addons\gut\cli\optparse.gd.uid" />
    <Content Include="addons\gut\collected_script.gd" />
    <Content Include="addons\gut\collected_script.gd.uid" />
    <Content Include="addons\gut\collected_test.gd" />
    <Content Include="addons\gut\collected_test.gd.uid" />
    <Content Include="addons\gut\comparator.gd" />
    <Content Include="addons\gut\comparator.gd.uid" />
    <Content Include="addons\gut\compare_result.gd" />
    <Content Include="addons\gut\compare_result.gd.uid" />
    <Content Include="addons\gut\diff_formatter.gd" />
    <Content Include="addons\gut\diff_formatter.gd.uid" />
    <Content Include="addons\gut\diff_tool.gd" />
    <Content Include="addons\gut\diff_tool.gd.uid" />
    <Content Include="addons\gut\doubler.gd" />
    <Content Include="addons\gut\doubler.gd.uid" />
    <Content Include="addons\gut\double_templates\function_template.txt" />
    <Content Include="addons\gut\double_templates\init_template.txt" />
    <Content Include="addons\gut\double_templates\script_template.txt" />
    <Content Include="addons\gut\double_tools.gd" />
    <Content Include="addons\gut\double_tools.gd.uid" />
    <Content Include="addons\gut\dynamic_gdscript.gd" />
    <Content Include="addons\gut\dynamic_gdscript.gd.uid" />
    <Content Include="addons\gut\editor_caret_context_notifier.gd" />
    <Content Include="addons\gut\editor_caret_context_notifier.gd.uid" />
    <Content Include="addons\gut\error_tracker.gd" />
    <Content Include="addons\gut\error_tracker.gd.uid" />
    <Content Include="addons\gut\fonts\AnonymousPro-Bold.ttf" />
    <Content Include="addons\gut\fonts\AnonymousPro-Bold.ttf.import" />
    <Content Include="addons\gut\fonts\AnonymousPro-BoldItalic.ttf" />
    <Content Include="addons\gut\fonts\AnonymousPro-BoldItalic.ttf.import" />
    <Content Include="addons\gut\fonts\AnonymousPro-Italic.ttf" />
    <Content Include="addons\gut\fonts\AnonymousPro-Italic.ttf.import" />
    <Content Include="addons\gut\fonts\AnonymousPro-Regular.ttf" />
    <Content Include="addons\gut\fonts\AnonymousPro-Regular.ttf.import" />
    <Content Include="addons\gut\fonts\CourierPrime-Bold.ttf" />
    <Content Include="addons\gut\fonts\CourierPrime-Bold.ttf.import" />
    <Content Include="addons\gut\fonts\CourierPrime-BoldItalic.ttf" />
    <Content Include="addons\gut\fonts\CourierPrime-BoldItalic.ttf.import" />
    <Content Include="addons\gut\fonts\CourierPrime-Italic.ttf" />
    <Content Include="addons\gut\fonts\CourierPrime-Italic.ttf.import" />
    <Content Include="addons\gut\fonts\CourierPrime-Regular.ttf" />
    <Content Include="addons\gut\fonts\CourierPrime-Regular.ttf.import" />
    <Content Include="addons\gut\fonts\LobsterTwo-Bold.ttf" />
    <Content Include="addons\gut\fonts\LobsterTwo-Bold.ttf.import" />
    <Content Include="addons\gut\fonts\LobsterTwo-BoldItalic.ttf" />
    <Content Include="addons\gut\fonts\LobsterTwo-BoldItalic.ttf.import" />
    <Content Include="addons\gut\fonts\LobsterTwo-Italic.ttf" />
    <Content Include="addons\gut\fonts\LobsterTwo-Italic.ttf.import" />
    <Content Include="addons\gut\fonts\LobsterTwo-Regular.ttf" />
    <Content Include="addons\gut\fonts\LobsterTwo-Regular.ttf.import" />
    <Content Include="addons\gut\fonts\OFL.txt" />
    <Content Include="addons\gut\get_editor_interface.gd" />
    <Content Include="addons\gut\get_editor_interface.gd.uid" />
    <Content Include="addons\gut\gui\about.gd" />
    <Content Include="addons\gut\gui\about.gd.uid" />
    <Content Include="addons\gut\gui\about.tscn" />
    <Content Include="addons\gut\gui\arrow.png" />
    <Content Include="addons\gut\gui\arrow.png.import" />
    <Content Include="addons\gut\gui\EditorRadioButton.tres" />
    <Content Include="addons\gut\gui\editor_globals.gd" />
    <Content Include="addons\gut\gui\editor_globals.gd.uid" />
    <Content Include="addons\gut\gui\GutBottomPanel.gd" />
    <Content Include="addons\gut\gui\GutBottomPanel.gd.uid" />
    <Content Include="addons\gut\gui\GutBottomPanel.tscn" />
    <Content Include="addons\gut\gui\GutControl.gd" />
    <Content Include="addons\gut\gui\GutControl.gd.uid" />
    <Content Include="addons\gut\gui\GutControl.tscn" />
    <Content Include="addons\gut\gui\GutEditorWindow.gd" />
    <Content Include="addons\gut\gui\GutEditorWindow.gd.uid" />
    <Content Include="addons\gut\gui\GutEditorWindow.tscn" />
    <Content Include="addons\gut\gui\GutLogo.tscn" />
    <Content Include="addons\gut\gui\GutRunner.gd" />
    <Content Include="addons\gut\gui\GutRunner.gd.uid" />
    <Content Include="addons\gut\gui\GutRunner.tscn" />
    <Content Include="addons\gut\gui\GutSceneTheme.tres" />
    <Content Include="addons\gut\gui\gut_config_gui.gd" />
    <Content Include="addons\gut\gui\gut_config_gui.gd.uid" />
    <Content Include="addons\gut\gui\gut_gui.gd" />
    <Content Include="addons\gut\gui\gut_gui.gd.uid" />
    <Content Include="addons\gut\gui\gut_logo.gd" />
    <Content Include="addons\gut\gui\gut_logo.gd.uid" />
    <Content Include="addons\gut\gui\gut_user_preferences.gd" />
    <Content Include="addons\gut\gui\gut_user_preferences.gd.uid" />
    <Content Include="addons\gut\gui\MinGui.tscn" />
    <Content Include="addons\gut\gui\NormalGui.tscn" />
    <Content Include="addons\gut\gui\option_maker.gd" />
    <Content Include="addons\gut\gui\option_maker.gd.uid" />
    <Content Include="addons\gut\gui\OutputText.gd" />
    <Content Include="addons\gut\gui\OutputText.gd.uid" />
    <Content Include="addons\gut\gui\OutputText.tscn" />
    <Content Include="addons\gut\gui\panel_controls.gd" />
    <Content Include="addons\gut\gui\panel_controls.gd.uid" />
    <Content Include="addons\gut\gui\play.png" />
    <Content Include="addons\gut\gui\play.png.import" />
    <Content Include="addons\gut\gui\ResizeHandle.gd" />
    <Content Include="addons\gut\gui\ResizeHandle.gd.uid" />
    <Content Include="addons\gut\gui\ResizeHandle.tscn" />
    <Content Include="addons\gut\gui\ResultsTree.gd" />
    <Content Include="addons\gut\gui\ResultsTree.gd.uid" />
    <Content Include="addons\gut\gui\ResultsTree.tscn" />
    <Content Include="addons\gut\gui\RunAtCursor.gd" />
    <Content Include="addons\gut\gui\RunAtCursor.gd.uid" />
    <Content Include="addons\gut\gui\RunAtCursor.tscn" />
    <Content Include="addons\gut\gui\RunExternally.gd" />
    <Content Include="addons\gut\gui\RunExternally.gd.uid" />
    <Content Include="addons\gut\gui\RunExternally.tscn" />
    <Content Include="addons\gut\gui\RunResults.gd" />
    <Content Include="addons\gut\gui\RunResults.gd.uid" />
    <Content Include="addons\gut\gui\RunResults.tscn" />
    <Content Include="addons\gut\gui\run_from_editor.gd" />
    <Content Include="addons\gut\gui\run_from_editor.gd.uid" />
    <Content Include="addons\gut\gui\run_from_editor.tscn" />
    <Content Include="addons\gut\gui\Settings.tscn" />
    <Content Include="addons\gut\gui\ShellOutOptions.gd" />
    <Content Include="addons\gut\gui\ShellOutOptions.gd.uid" />
    <Content Include="addons\gut\gui\ShellOutOptions.tscn" />
    <Content Include="addons\gut\gui\ShortcutButton.gd" />
    <Content Include="addons\gut\gui\ShortcutButton.gd.uid" />
    <Content Include="addons\gut\gui\ShortcutButton.tscn" />
    <Content Include="addons\gut\gui\ShortcutDialog.gd" />
    <Content Include="addons\gut\gui\ShortcutDialog.gd.uid" />
    <Content Include="addons\gut\gui\ShortcutDialog.tscn" />
    <Content Include="addons\gut\gut.gd" />
    <Content Include="addons\gut\gut.gd.uid" />
    <Content Include="addons\gut\GutScene.gd" />
    <Content Include="addons\gut\GutScene.gd.uid" />
    <Content Include="addons\gut\GutScene.tscn" />
    <Content Include="addons\gut\gut_cmdln.gd" />
    <Content Include="addons\gut\gut_cmdln.gd.uid" />
    <Content Include="addons\gut\gut_config.gd" />
    <Content Include="addons\gut\gut_config.gd.uid" />
    <Content Include="addons\gut\gut_fonts.gd" />
    <Content Include="addons\gut\gut_fonts.gd.uid" />
    <Content Include="addons\gut\gut_loader.gd" />
    <Content Include="addons\gut\gut_loader.gd.uid" />
    <Content Include="addons\gut\gut_loader_the_scene.tscn" />
    <Content Include="addons\gut\gut_menu.gd" />
    <Content Include="addons\gut\gut_menu.gd.uid" />
    <Content Include="addons\gut\gut_plugin.gd" />
    <Content Include="addons\gut\gut_plugin.gd.uid" />
    <Content Include="addons\gut\gut_to_move.gd" />
    <Content Include="addons\gut\gut_to_move.gd.uid" />
    <Content Include="addons\gut\gut_tracked_error.gd" />
    <Content Include="addons\gut\gut_tracked_error.gd.uid" />
    <Content Include="addons\gut\gut_vscode_debugger.gd" />
    <Content Include="addons\gut\gut_vscode_debugger.gd.uid" />
    <Content Include="addons\gut\hook_script.gd" />
    <Content Include="addons\gut\hook_script.gd.uid" />
    <Content Include="addons\gut\icon.png" />
    <Content Include="addons\gut\icon.png.import" />
    <Content Include="addons\gut\images\eyey.png" />
    <Content Include="addons\gut\images\eyey.png.import" />
    <Content Include="addons\gut\images\Folder.svg" />
    <Content Include="addons\gut\images\Folder.svg.import" />
    <Content Include="addons\gut\images\green.png" />
    <Content Include="addons\gut\images\green.png.import" />
    <Content Include="addons\gut\images\GutIconV2_base.png" />
    <Content Include="addons\gut\images\GutIconV2_base.png.import" />
    <Content Include="addons\gut\images\GutIconV2_no_shine.png" />
    <Content Include="addons\gut\images\GutIconV2_no_shine.png.import" />
    <Content Include="addons\gut\images\HSplitContainer.svg" />
    <Content Include="addons\gut\images\HSplitContainer.svg.import" />
    <Content Include="addons\gut\images\red.png" />
    <Content Include="addons\gut\images\red.png.import" />
    <Content Include="addons\gut\images\Script.svg" />
    <Content Include="addons\gut\images\Script.svg.import" />
    <Content Include="addons\gut\images\VSplitContainer.svg" />
    <Content Include="addons\gut\images\VSplitContainer.svg.import" />
    <Content Include="addons\gut\images\yellow.png" />
    <Content Include="addons\gut\images\yellow.png.import" />
    <Content Include="addons\gut\inner_class_registry.gd" />
    <Content Include="addons\gut\inner_class_registry.gd.uid" />
    <Content Include="addons\gut\input_factory.gd" />
    <Content Include="addons\gut\input_factory.gd.uid" />
    <Content Include="addons\gut\input_sender.gd" />
    <Content Include="addons\gut\input_sender.gd.uid" />
    <Content Include="addons\gut\junit_xml_export.gd" />
    <Content Include="addons\gut\junit_xml_export.gd.uid" />
    <Content Include="addons\gut\lazy_loader.gd" />
    <Content Include="addons\gut\lazy_loader.gd.uid" />
    <Content Include="addons\gut\LICENSE.md" />
    <Content Include="addons\gut\logger.gd" />
    <Content Include="addons\gut\logger.gd.uid" />
    <Content Include="addons\gut\menu_manager.gd.uid" />
    <Content Include="addons\gut\method_maker.gd" />
    <Content Include="addons\gut\method_maker.gd.uid" />
    <Content Include="addons\gut\one_to_many.gd" />
    <Content Include="addons\gut\one_to_many.gd.uid" />
    <Content Include="addons\gut\orphan_counter.gd" />
    <Content Include="addons\gut\orphan_counter.gd.uid" />
    <Content Include="addons\gut\parameter_factory.gd" />
    <Content Include="addons\gut\parameter_factory.gd.uid" />
    <Content Include="addons\gut\parameter_handler.gd" />
    <Content Include="addons\gut\parameter_handler.gd.uid" />
    <Content Include="addons\gut\plugin.cfg" />
    <Content Include="addons\gut\printers.gd" />
    <Content Include="addons\gut\printers.gd.uid" />
    <Content Include="addons\gut\result_exporter.gd" />
    <Content Include="addons\gut\result_exporter.gd.uid" />
    <Content Include="addons\gut\script_parser.gd" />
    <Content Include="addons\gut\script_parser.gd.uid" />
    <Content Include="addons\gut\signal_watcher.gd" />
    <Content Include="addons\gut\signal_watcher.gd.uid" />
    <Content Include="addons\gut\source_code_pro.fnt" />
    <Content Include="addons\gut\source_code_pro.fnt.import" />
    <Content Include="addons\gut\spy.gd" />
    <Content Include="addons\gut\spy.gd.uid" />
    <Content Include="addons\gut\strutils.gd" />
    <Content Include="addons\gut\strutils.gd.uid" />
    <Content Include="addons\gut\stubber.gd" />
    <Content Include="addons\gut\stubber.gd.uid" />
    <Content Include="addons\gut\stub_params.gd" />
    <Content Include="addons\gut\stub_params.gd.uid" />
    <Content Include="addons\gut\summary.gd" />
    <Content Include="addons\gut\summary.gd.uid" />
    <Content Include="addons\gut\test.gd" />
    <Content Include="addons\gut\test.gd.uid" />
    <Content Include="addons\gut\test_collector.gd" />
    <Content Include="addons\gut\test_collector.gd.uid" />
    <Content Include="addons\gut\thing_counter.gd" />
    <Content Include="addons\gut\thing_counter.gd.uid" />
    <Content Include="addons\gut\UserFileViewer.gd" />
    <Content Include="addons\gut\UserFileViewer.gd.uid" />
    <Content Include="addons\gut\UserFileViewer.tscn" />
    <Content Include="addons\gut\utils.gd" />
    <Content Include="addons\gut\utils.gd.uid" />
    <Content Include="addons\gut\version_conversion.gd" />
    <Content Include="addons\gut\version_conversion.gd.uid" />
    <Content Include="addons\gut\version_numbers.gd" />
    <Content Include="addons\gut\version_numbers.gd.uid" />
    <Content Include="addons\gut\warnings_manager.gd" />
    <Content Include="addons\gut\warnings_manager.gd.uid" />
    <Content Include="domain\animal_spot\animal_spot_handler.gd" />
    <Content Include="domain\animal_spot\animal_spot_handler.gd.uid" />
    <Content Include="domain\animal_spot\delete_existing_animal_spots_command.gd" />
    <Content Include="domain\animal_spot\delete_existing_animal_spots_command.gd.uid" />
    <Content Include="domain\animal_spot\find_all_animal_spots_by_date_query.gd" />
    <Content Include="domain\animal_spot\find_all_animal_spots_by_date_query.gd.uid" />
    <Content Include="domain\animal_spot\find_all_animal_spots_by_query.gd" />
    <Content Include="domain\animal_spot\find_all_animal_spots_by_query.gd.uid" />
    <Content Include="domain\animal_spot\find_all_animal_spot_animal_names_query.gd" />
    <Content Include="domain\animal_spot\find_all_animal_spot_animal_names_query.gd.uid" />
    <Content Include="domain\animal_spot\find_all_animal_spot_dates_query.gd" />
    <Content Include="domain\animal_spot\find_all_animal_spot_dates_query.gd.uid" />
    <Content Include="domain\camera\camera_handler.gd" />
    <Content Include="domain\camera\camera_handler.gd.uid" />
    <Content Include="domain\camera\create_camera_command.gd" />
    <Content Include="domain\camera\create_camera_command.gd.uid" />
    <Content Include="domain\camera\delete_camera_command.gd" />
    <Content Include="domain\camera\delete_camera_command.gd.uid" />
    <Content Include="domain\camera\find_all_cameras_query.gd" />
    <Content Include="domain\camera\find_all_cameras_query.gd.uid" />
    <Content Include="domain\camera\fs_camera.gd" />
    <Content Include="domain\camera\fs_camera.gd.uid" />
    <Content Include="domain\camera\fs_camera_repository.gd" />
    <Content Include="domain\camera\fs_camera_repository.gd.uid" />
    <Content Include="domain\camera\update_camera_command.gd" />
    <Content Include="domain\camera\update_camera_command.gd.uid" />
    <Content Include="domain\command_query_dispatcher.gd" />
    <Content Include="domain\command_query_dispatcher.gd.uid" />
    <Content Include="domain\handler\command_query_handler.gd" />
    <Content Include="domain\handler\command_query_handler.gd.uid" />
    <Content Include="domain\images\compute_image_hash_query.gd" />
    <Content Include="domain\images\compute_image_hash_query.gd.uid" />
    <Content Include="domain\images\fs_processed_image_repository.gd" />
    <Content Include="domain\images\fs_processed_image_repository.gd.uid" />
    <Content Include="domain\images\get_exif_info_query.gd" />
    <Content Include="domain\images\get_exif_info_query.gd.uid" />
    <Content Include="domain\images\has_image_been_processed_query.gd" />
    <Content Include="domain\images\has_image_been_processed_query.gd.uid" />
    <Content Include="domain\images\processed_image_handler.gd" />
    <Content Include="domain\images\processed_image_handler.gd.uid" />
    <Content Include="domain\settings\settings.gd" />
    <Content Include="domain\settings\settings.gd.uid" />
    <Content Include="icon.svg" />
    <Content Include="icon.svg.import" />
    <Content Include="icons\question_mark.png" />
    <Content Include="icons\question_mark.png.import" />
    <Content Include="infrastructure\database_manager_sqlite.gd" />
    <Content Include="infrastructure\database_manager_sqlite.gd.uid" />
    <Content Include="infrastructure\ExifInfo.cs.uid" />
    <Content Include="infrastructure\ExifReader.cs.uid" />
    <Content Include="infrastructure\file_hasher.gd" />
    <Content Include="infrastructure\file_hasher.gd.uid" />
    <Content Include="infrastructure\gbif\gbif_client.gd" />
    <Content Include="infrastructure\gbif\gbif_client.gd.uid" />
    <Content Include="infrastructure\gbif\gbif_search_error_result.gd" />
    <Content Include="infrastructure\gbif\gbif_search_error_result.gd.uid" />
    <Content Include="infrastructure\gbif\gbif_search_result.gd" />
    <Content Include="infrastructure\gbif\gbif_search_result.gd.uid" />
    <Content Include="infrastructure\http_requester.gd" />
    <Content Include="infrastructure\http_requester.gd.uid" />
    <Content Include="infrastructure\image_utils.gd" />
    <Content Include="infrastructure\phylopic\phylopic_client.gd" />
    <Content Include="infrastructure\phylopic\phylopic_client.gd.uid" />
    <Content Include="infrastructure\sqlite_fs_camera_repsository.gd" />
    <Content Include="infrastructure\sqlite_fs_camera_repsository.gd.uid" />
    <Content Include="infrastructure\sqlite_fs_processed_image_repository.gd" />
    <Content Include="infrastructure\sqlite_fs_processed_image_repository.gd.uid" />
    <Content Include="LICENSE" />
    <Content Include="main.tscn" />
    <Content Include="project.godot" />
    <Content Include="Readme.md" />
    <Content Include="test\contracts\test_gbif_client_search_by_vernacular_name_contract.gd" />
    <Content Include="test\contracts\test_gbif_client_search_by_vernacular_name_contract.gd.uid" />
    <Content Include="test\contracts\test_phylopic_client_find_picture_for_gbif_item_contract.gd" />
    <Content Include="test\contracts\test_phylopic_client_find_picture_for_gbif_item_contract.gd.uid" />
    <Content Include="test\fixtures\common_blackbird_phylopic.licence.txt" />
    <Content Include="test\fixtures\common_blackbird_phylopic.png" />
    <Content Include="test\fixtures\common_blackbird_phylopic.png.import" />
    <Content Include="test\fixtures\fixtures.gd" />
    <Content Include="test\fixtures\fixtures.gd.uid" />
    <Content Include="test\fixtures\fixture_image1.jpg" />
    <Content Include="test\fixtures\fixture_image1.jpg.import" />
    <Content Include="test\fixtures\fixture_image2.jpg" />
    <Content Include="test\fixtures\fixture_image2.jpg.import" />
    <Content Include="test\fixtures\nightingale.png" />
    <Content Include="test\fixtures\nightingale.png.import" />
    <Content Include="test\generators\animal_spot_generator.gd" />
    <Content Include="test\generators\animal_spot_generator.gd.uid" />
    <Content Include="test\generators\command_query_handler_generator.gd" />
    <Content Include="test\generators\command_query_handler_generator.gd.uid" />
    <Content Include="test\generators\exif_info_generator.gd" />
    <Content Include="test\generators\exif_info_generator.gd.uid" />
    <Content Include="test\integration\infrastructure\test_animal_spot_repository_sqlite_find_all_distinct_animal_names.gd" />
    <Content Include="test\integration\infrastructure\test_animal_spot_repository_sqlite_find_all_distinct_animal_names.gd.uid" />
    <Content Include="test\integration\infrastructure\test_animal_spot_repsitory_sqlite.gd" />
    <Content Include="test\integration\infrastructure\test_animal_spot_repsitory_sqlite.gd.uid" />
    <Content Include="test\integration\infrastructure\test_animal_spot_repsitory_sqlite_find_all_by.gd" />
    <Content Include="test\integration\infrastructure\test_animal_spot_repsitory_sqlite_find_all_by.gd.uid" />
    <Content Include="test\integration\infrastructure\test_exif_reader.gd" />
    <Content Include="test\integration\infrastructure\test_exif_reader.gd.uid" />
    <Content Include="test\integration\infrastructure\test_sqlite_fs_processed_images_repository.gd" />
    <Content Include="test\integration\infrastructure\test_sqlite_fs_processed_images_repository.gd.uid" />
    <Content Include="test\integration\ui\spots\test_bulk_spot_window.gd" />
    <Content Include="test\integration\ui\spots\test_bulk_spot_window.gd.uid" />
    <Content Include="test\integration\ui\spots\test_bulk_spot_window_preprocess_progress.gd" />
    <Content Include="test\integration\ui\spots\test_bulk_spot_window_preprocess_progress.gd.uid" />
    <Content Include="test\integration\ui\test_toast_bar.gd" />
    <Content Include="test\integration\ui\test_toast_bar.gd.uid" />
    <Content Include="ui\animal_pictogram_search\animal_pictogram_search.gd" />
    <Content Include="ui\animal_pictogram_search\animal_pictogram_search.gd.uid" />
    <Content Include="ui\animal_pictogram_search\animal_pictogram_search.tscn" />
    <Content Include="ui\cameras\cameras_window.gd" />
    <Content Include="ui\cameras\cameras_window.gd.uid" />
    <Content Include="ui\cameras\cameras_window.tscn" />
    <Content Include="ui\components\stack_container.gd" />
    <Content Include="ui\components\stack_container.gd.uid" />
    <Content Include="ui\components\stack_container.tscn" />
    <Content Include="ui\file_dialog_manager.gd" />
    <Content Include="ui\file_dialog_manager.gd.uid" />
    <Content Include="ui\file_dialog_manager.tscn" />
    <Content Include="ui\image_viewer.gd" />
    <Content Include="ui\image_viewer.gd.uid" />
    <Content Include="ui\image_viewer.tscn" />
    <Content Include="ui\main_ui.gd" />
    <Content Include="ui\main_ui.gd.uid" />
    <Content Include="ui\main_ui.tscn" />
    <Content Include="ui\reports\report_control.gd" />
    <Content Include="ui\reports\report_control.gd.uid" />
    <Content Include="ui\reports\report_control.tscn" />
    <Content Include="ui\reports\spot_chart.gd" />
    <Content Include="ui\reports\spot_chart.gd.uid" />
    <Content Include="ui\select_database_dialog.gd" />
    <Content Include="ui\select_database_dialog.gd.uid" />
    <Content Include="ui\select_database_dialog.tscn" />
    <Content Include="ui\settings\animal_settings.gd" />
    <Content Include="ui\settings\animal_settings.gd.uid" />
    <Content Include="ui\settings\animal_settings.tscn" />
    <Content Include="ui\settings\image_settings.gd" />
    <Content Include="ui\settings\image_settings.gd.uid" />
    <Content Include="ui\settings\image_settings.tscn" />
    <Content Include="ui\settings\settings_window.gd" />
    <Content Include="ui\settings\settings_window.gd.uid" />
    <Content Include="ui\settings\settings_window.tscn" />
    <Content Include="ui\spots\animal_box.gd" />
    <Content Include="ui\spots\animal_box.gd.uid" />
    <Content Include="ui\spots\animal_box.tscn" />
    <Content Include="ui\spots\bulk_spot_window.gd" />
    <Content Include="ui\spots\bulk_spot_window.gd.uid" />
    <Content Include="ui\spots\bulk_spot_window.tscn" />
    <Content Include="ui\spots\image_preprocessor.gd" />
    <Content Include="ui\spots\image_preprocessor.gd.uid" />
    <Content Include="ui\spots\manage_spots_window.gd" />
    <Content Include="ui\spots\manage_spots_window.gd.uid" />
    <Content Include="ui\spots\manage_spots_window.tscn" />
    <Content Include="ui\theming\itemlist_selected_stylebox.tres" />
    <Content Include="ui\theming\panel_stylebox.tres" />
    <Content Include="ui\theming\theme.tres" />
    <Content Include="ui\toast_bar.gd" />
    <Content Include="ui\toast_bar.gd.uid" />
    <Content Include="ui\toast_bar.tscn" />
    <Content Include="update_easy_charts.sh" />
    <Content Include="WildLifeSpot.sln" />
  </ItemGroup>
</Project>
